version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: medicare-postgres
    environment:
      POSTGRES_DB: medicare_ai
      POSTGRES_USER: medicare_user
      POSTGRES_PASSWORD: medicare_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - medicare-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: medicare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medicare-network

  # MediCare AI Application
  app:
    build: .
    container_name: medicare-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://medicare_user:medicare_password@postgres:5432/medicare_ai?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - medicare-network
    volumes:
      - ./uploads:/app/uploads

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: medicare-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - medicare-network

volumes:
  postgres_data:
  redis_data:

networks:
  medicare-network:
    driver: bridge




