services:
  # MediCare AI Web Service
  - type: web
    name: medicare-ai
    env: node
    plan: starter
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma migrate deploy
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: medicare-ai
          property: host
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: medicare-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: medicare-redis
          property: connectionString
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_VISION_API_KEY
        sync: false
      - key: FDA_API_KEY
        sync: false
      - key: DRUG_INTERACTION_API_KEY
        sync: false

  # PostgreSQL Database
  - type: pserv
    name: medicare-db
    env: postgresql
    plan: starter
    disk:
      name: medicare-db-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

  # Redis Cache
  - type: redis
    name: medicare-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru

